[book]
authors = ["John Baldwin", "Jessica Clarke", "Brooks Davis", "Wes Filardo", "Robert N. M. Watson"]
language = "en"
multilingual = false
src = "src"
title = "SOSP 2023 CHERI Tutorial Exercises"

[output.html]
git-repository-url = "https://github.com/CTSRD-CHERI/cheri-exercises"
site-url = "/cheri-exercises/"
